name: Deploy React App to S3

on:
  push:
    branches:
      - main # or whichever branch you want to trigger the deployment

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Check out the code
      - name: Checkout code
        uses: actions/checkout@v2

      # Step 2: Set up Node.js (specify your Node version)
      - name: Set up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: "16" # Match the version you use locally

      # Step 3: Install dependencies and build the project
      - name: Install dependencies and build
        run: |
          npm install ./frontend
          npm --prefix ./frontend run build

      # Step 4: sync S3
      - name: Push build to S3
        uses: sai-sharan/aws-s3-sync-action@master
        with:
          access_key: ${{ secrets.AWS_ACCESS_KEY_ID }}
          secret_access_key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          region: ${{ secrets.AWS_REGION }}
          source: "frontend/build"
          destination_bucket: ${{ secrets.S3_BUCKET_NAME }}
          destination_prefix: s3://
          exclude: ".git/*"
          delete: true
          quiet: false
